1. Nhóm giải thuật phân lớp
<p>Giải thuật có giám sát là khi đã có input và output trong tập dữ liệu</>
<p>Giải thuật không giám sát là khi không có output trong tập dữ liệu</>

<div> - KNN</>
<p>Lưu trữ dữ liệu mà không trích rút tri thức. Dựa vào thiết lập giá trị cao trong 5 phần tử để rút ra được kết quả các nhãn được xuất hiện nhiều nhất để kết luận</>

<p> Ngưỡng quyết định
<p>Xác xuất tìm quyết định là xác xuất của các nhãn phân loại khi đi qua mô hình trước khi được quyết định
<p>Ngưỡng quyết định là mốc để đưa ra quyết định

<p>Trên cây quyết định not là đặc trưng, play là quyết định
<p>Các giải thuật: ID3, C4.5, CART
<p> Hệ số căn bản cần học: Entropy và InformationGain (IG)

In [1]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np

#B1
df = pd.read_excel('heart_short.xlsx',sheet_name="data")
df

t_i  c_i  result          d
0   145  233       1  33.376639
1   130  250       1  53.851648
2   130  204       1  20.396078
3   130  254       0  57.584720
4   140  203       0  10.440307
5   130  256       0  59.464275
6   140  294       1  94.530418
7   120  263       1  69.778220
8   172  199       1  22.022716
9   150  168       1  32.000000
10  120  229       0  41.725292
11  140  268       0  68.731361

In [2]:
#B2
X = df[['t_i', 'c_i']].values #input
y = df[['result']].values #output

X = X.astype(float)
y = y.astype(float)

In [3]:
#B3
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.4, random_state=34)

In [4]:
from sklearn.neighbors import KNeighborsClassifier
knnModel = KNeighborsClassifier(n_neighbors=5)
knnModel.fit(X_train, y_train)

c:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\neighbors\_classification.py:228: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


KNeighborsClassifier()

In [5]:
y_test_predicted =knnModel.predict(X_test)
y_test_predicted

array([0., 0., 0., 0., 0.])

In [6]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_test_predicted)

0.2

In [7]:
knnModel.score(X_test, y_test)

0.2

In [8]:
classes = knnModel.classes_
classes

array([0., 1.])

In [9]:
y_test_prob = knnModel.predict_proba(X_test)
y_test_prob

array([[0.8, 0.2],
       [0.6, 0.4],
       [0.6, 0.4],
       [0.6, 0.4],
       [0.6, 0.4]])

In [10]:
print('prediction with threshold 0.85:') 
y_pred_test_085 = (knnModel.predict_proba(X_test)[:, 1] >= 0.85).astype(float) 
y_pred_test_085

prediction with threshold 0.85:


array([0., 0., 0., 0., 0.])

In [11]:
print('prediction with threshold 0.25:') 
y_pred_test_025 = (knnModel.predict_proba(X_test) [:, 1] >= 0.25).astype (float) 
y_pred_test_025

prediction with threshold 0.25:


array([0., 1., 1., 1., 1.])

In [12]:
from sklearn.metrics import confusion_matrix
cf_matrix = confusion_matrix(y_test, y_test_predicted)
cf_matrix

array([[1, 0],
       [4, 0]], dtype=int64)

In [13]:
tn, fp, fn, tp = confusion_matrix(y_test, y_test_predicted).ravel()
tn, fp, fn, tp

(1, 0, 4, 0)